services:
  redis:
    image: redis:7.0.9-alpine
    command: redis-server --bind 0.0.0.0
    ports:
      - 6379:6379
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    container_name: vocode-telephony-app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      - REDISHOST=redis
    volumes:
      - .:/code
